name: Test

on:
    workflow_dispatch:


env:
    # Needed for GitHub CLI
    GITHUB_TOKEN: ${{ github.token }}

defaults:
    run:
        shell: pwsh

jobs:
    close_milestone:
        runs-on: ubuntu-latest
        name: Close Milestone

        steps:
            # Checkout is needed so that we can update the get_versions.yml file
            - uses: actions/checkout@v4

            - name: Increment Version Numbers
              run: |
                  function Update-Version {
                      param (
                        [string]$Prefix
                      )
                      $workflowPath = "./.github/workflows/get_versions.yml"
                      $workflowContent = Get-Content -Path $workflowPath

                      $versionPattern = '"(\d+\.\d+\.)(\d+)"'
                      $pattern = "$Prefix`: $versionPattern"
                      $match = $workflowContent -match $pattern

                      if ($match[0] -match $versionPattern) {
                          $newVersion = $Matches[1] + ([int]$Matches[2] + 1)
                          $workflowContent = $workflowContent -replace $pattern,"$Prefix`: `"$newVersion`""
                          Write-Host "$Prefix updated to $newVersion"
                      } else {
                          Write-Error "Failed to update $Prefix version"
                      }

                      Set-Content -Path $workflowPath -Value $workflowContent
                  }

                  Update-Version -Prefix "mdix-version"
                  Update-Version -Prefix "mdix-colors-version"
                  Update-Version -Prefix "mdix-mahapps-version"

            - name: Push Changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -m "[automated] Increment version numbers after release of ${{ inputs.milestone }}" --all
                  git remote set-url origin https://${{ secrets.SA_PAT }}@github.com/${{ github.repository }}
                  git push
